export const ALL_HEROES = {
  'Anti-Mage': 'antimage',
  Axe: 'axe',
  Bane: 'bane',
  Bloodseeker: 'bloodseeker',
  'Crystal Maiden': 'crystal_maiden',
  'Drow Ranger': 'drow_ranger',
  Earthshaker: 'earthshaker',
  Juggernaut: 'juggernaut',
  Mirana: 'mirana',
  'Shadow Fiend': 'nevermore',
  Morphling: 'morphling',
  'Phantom Lancer': 'phantom_lancer',
  Puck: 'puck',
  Pudge: 'pudge',
  Razor: 'razor',
  'Sand King': 'sand_king',
  'Storm Spirit': 'storm_spirit',
  Sven: 'sven',
  Tiny: 'tiny',
  'Vengeful Spirit': 'vengefulspirit',
  Windranger: 'windrunner',
  Zeus: 'zuus',
  Kunkka: 'kunkka',
  Lina: 'lina',
  Lich: 'lich',
  Lion: 'lion',
  'Shadow Shaman': 'shadow_shaman',
  Slardar: 'slardar',
  Tidehunter: 'tidehunter',
  'Witch Doctor': 'witch_doctor',
  Riki: 'riki',
  Enigma: 'enigma',
  Tinker: 'tinker',
  Sniper: 'sniper',
  Necrophos: 'necrolyte',
  Warlock: 'warlock',
  Beastmaster: 'beastmaster',
  'Queen of Pain': 'queenofpain',
  Venomancer: 'venomancer',
  'Faceless Void': 'faceless_void',
  'Wraith King': 'skeleton_king',
  'Death Prophet': 'death_prophet',
  'Phantom Assassin': 'phantom_assassin',
  Pugna: 'pugna',
  'Templar Assassin': 'templar_assassin',
  Viper: 'viper',
  Luna: 'luna',
  'Dragon Knight': 'dragon_knight',
  Dazzle: 'dazzle',
  Clockwerk: 'rattletrap',
  Leshrac: 'leshrac',
  "Nature's Prophet": 'furion',
  Lifestealer: 'life_stealer',
  'Dark Seer': 'dark_seer',
  Clinkz: 'clinkz',
  Omniknight: 'omniknight',
  Enchantress: 'enchantress',
  Huskar: 'huskar',
  'Night Stalker': 'night_stalker',
  Broodmother: 'broodmother',
  'Bounty Hunter': 'bounty_hunter',
  Weaver: 'weaver',
  Jakiro: 'jakiro',
  Batrider: 'batrider',
  Chen: 'chen',
  Spectre: 'spectre',
  Doom: 'doom_bringer',
  'Ancient Apparition': 'ancient_apparition',
  Ursa: 'ursa',
  'Spirit Breaker': 'spirit_breaker',
  Gyrocopter: 'gyrocopter',
  Alchemist: 'alchemist',
  Invoker: 'invoker',
  Silencer: 'silencer',
  'Outworld Destroyer': 'obsidian_destroyer',
  Lycan: 'lycan',
  Brewmaster: 'brewmaster',
  'Shadow Demon': 'shadow_demon',
  'Lone Druid': 'lone_druid',
  'Chaos Knight': 'chaos_knight',
  Meepo: 'meepo',
  'Treant Protector': 'treant',
  'Ogre Magi': 'ogre_magi',
  Undying: 'undying',
  Rubick: 'rubick',
  Disruptor: 'disruptor',
  'Nyx Assassin': 'nyx_assassin',
  'Naga Siren': 'naga_siren',
  'Keeper of the Light': 'keeper_of_the_light',
  Io: 'wisp',
  Visage: 'visage',
  Slark: 'slark',
  Medusa: 'medusa',
  'Troll Warlord': 'troll_warlord',
  'Centaur Warrunner': 'centaur',
  Magnus: 'magnataur',
  Timbersaw: 'shredder',
  Bristleback: 'bristleback',
  Tusk: 'tusk',
  'Skywrath Mage': 'skywrath_mage',
  Abaddon: 'abaddon',
  'Elder Titan': 'elder_titan',
  'Legion Commander': 'legion_commander',
  'Ember Spirit': 'ember_spirit',
  'Earth Spirit': 'earth_spirit',
  Terrorblade: 'terrorblade',
  Phoenix: 'phoenix',
  Oracle: 'oracle',
  Techies: 'techies',
  'Winter Wyvern': 'winter_wyvern',
  'Arc Warden': 'arc_warden',
  Underlord: 'abyssal_underlord',
  'Monkey King': 'monkey_king',
  Pangolier: 'pangolier',
  'Dark Willow': 'dark_willow',
  Grimstroke: 'grimstroke',
  Mars: 'mars',
  'Void Spirit': 'void_spirit',
  Snapfire: 'snapfire',
  Hoodwink: 'hoodwink',
  Dawnbreaker: 'dawnbreaker',
};

export const ALL_HERO_OPTIONS = Object.keys(ALL_HEROES).map((x) => ({
  value: x,
  label: x,
}));

export function getHeroInUrl(heroName) {
  return ALL_HEROES[heroName] || heroName.replace(/\s/g, '_').toLowerCase();
}
